In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score,recall_score
from sklearn.metrics import confusion_matrix,accuracy_score

In [4]:
df=pd.read_csv("BankCustomers.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df=df.drop(["RowNumber","Surname"],axis=1)

In [6]:
Geography=pd.get_dummies(df["Geography"],drop_first=True)
Gender=pd.get_dummies(df["Gender"],drop_first=True)
df=pd.concat([df,Geography,Gender],axis=1)
df=df.drop(["Geography","Gender"],axis=1)

In [7]:
Target_col=["Exited"]
CustomerId=["CustomerId"]
X=df[[x for x in df.columns if x not in Target_col+CustomerId]]
y=df["Exited"]

In [8]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
# Applying Grid Search to find the best model and the best parameters
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
    
Print("Acuraccy: " ,grid_search.best_score_)
Print("Best parameters: ",grid_search.best_params_)
predictions = classifier.predict(X_test)
confusion_matrix(y_test,predictions)
#confusion matrix
conf_matrix = confusion_matrix(y_test,predictions)
print("\n Classification report : \n",classification_report(y_test,predictions))
print("Test Accuracy   Score : ",accuracy_score(y_test,predictions))
print("Test F1   Score : ",f1_score(y_test,predictions))
print("\nTrain Accuracy   Score : ",accuracy_score(y_train,prediction_train))
print("Train F1   Score : ",f1_score(y_train, prediction_train))
print(conf_matrix)